exercise6
RomanLunev/JavaProSpring pull request #3
Opened 2024-10-22 05:34 UTC by RomanLunev

2024-10-22 07:26 UTC, Alexandr056 requested changes
- Добавить в процесс исполнения платежа выбор продукта, проверку его существования и достаточности средств на нем
не увидел решения данного пункта задания

2024-10-22 07:26 UTC, Alexandr056 commented on payments-core/src/main/java/org/example/configuration/SpringConfiguration.java
> +    log.info("Building RestTemplate bean");
а нужен ли лог?

2024-10-22 07:26 UTC, Alexandr056 commented on payments-core/src/main/java/org/example/controller/ProductController.java
> +  ProductService productService;
private final

2024-10-22 07:26 UTC, Alexandr056 commented on products/src/main/java/com/example/javaspringpro/repository/ProductRepository.java
> +@Repository
рано, еще не подключали, ваш сервис прекрасно работал на Hikari

2024-10-22 07:38 UTC, RomanLunev commented on products/src/main/java/com/example/javaspringpro/repository/ProductRepository.java
> +@Repository
Сделал как вы описывали на предыдущей лекции

2024-10-22 07:39 UTC, RomanLunev commented on payments-core/src/main/java/org/example/configuration/SpringConfiguration.java
> +    log.info("Building RestTemplate bean");
Уже не нуже удалю

2024-10-24 08:01 UTC, Alexandr056 approved these changes
хорошая работа над ошибками

2024-10-24 08:01 UTC, Alexandr056 commented on products/src/main/java/com/example/javaspringpro/controller/ProductController.java
> +    return product;
inline variable

2024-10-24 08:01 UTC, Alexandr056 commented on products/src/main/java/com/example/javaspringpro/repository/ProductRepository.java
> +@Repository
я так и понял что это и смутило…

2024-10-24 08:04 UTC, merged